"""First migration

Revision ID: 1bc286718061
Revises: 2ba49bc09b57
Create Date: 2023-04-01 02:35:01.464339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc286718061'
down_revision = '2ba49bc09b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
